/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as PasswordResetSuccessRouteImport } from './routes/password-reset-success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAllDsasRouteImport } from './routes/dashboard.all-dsas'
import { Route as DashboardBalanceMovementsRouteImport } from './routes/dashboard.balance-movements'
import { Route as DashboardKpiPerformanceRouteImport } from './routes/dashboard.kpi-performance'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetSuccessRoute = PasswordResetSuccessRouteImport.update({
  id: '/password-reset-success',
  path: '/password-reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAllDsasRoute = DashboardAllDsasRouteImport.update({
  id: '/all-dsas',
  path: '/all-dsas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBalanceMovementsRoute =
  DashboardBalanceMovementsRouteImport.update({
    id: '/balance-movements',
    path: '/balance-movements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardKpiPerformanceRoute = DashboardKpiPerformanceRouteImport.update({
  id: '/kpi-performance',
  path: '/kpi-performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/create-password': typeof CreatePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/all-dsas': typeof DashboardAllDsasRoute
  '/dashboard/balance-movements': typeof DashboardBalanceMovementsRoute
  '/dashboard/kpi-performance': typeof DashboardKpiPerformanceRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/create-password': typeof CreatePasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/all-dsas': typeof DashboardAllDsasRoute
  '/dashboard/balance-movements': typeof DashboardBalanceMovementsRoute
  '/dashboard/kpi-performance': typeof DashboardKpiPerformanceRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/create-password': typeof CreatePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/password-reset-success': typeof PasswordResetSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/all-dsas': typeof DashboardAllDsasRoute
  '/dashboard/balance-movements': typeof DashboardBalanceMovementsRoute
  '/dashboard/kpi-performance': typeof DashboardKpiPerformanceRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/create-password'
    | '/dashboard'
    | '/login'
    | '/otp'
    | '/password-reset-success'
    | '/reset-password'
    | '/dashboard/all-dsas'
    | '/dashboard/balance-movements'
    | '/dashboard/kpi-performance'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/create-password'
    | '/login'
    | '/otp'
    | '/password-reset-success'
    | '/reset-password'
    | '/dashboard/all-dsas'
    | '/dashboard/balance-movements'
    | '/dashboard/kpi-performance'
    | '/dashboard/transactions'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/create-password'
    | '/dashboard'
    | '/login'
    | '/otp'
    | '/password-reset-success'
    | '/reset-password'
    | '/dashboard/all-dsas'
    | '/dashboard/balance-movements'
    | '/dashboard/kpi-performance'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CreatePasswordRoute: typeof CreatePasswordRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  PasswordResetSuccessRoute: typeof PasswordResetSuccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset-success': {
      id: '/password-reset-success'
      path: '/password-reset-success'
      fullPath: '/password-reset-success'
      preLoaderRoute: typeof PasswordResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/all-dsas': {
      id: '/dashboard/all-dsas'
      path: '/all-dsas'
      fullPath: '/dashboard/all-dsas'
      preLoaderRoute: typeof DashboardAllDsasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/balance-movements': {
      id: '/dashboard/balance-movements'
      path: '/balance-movements'
      fullPath: '/dashboard/balance-movements'
      preLoaderRoute: typeof DashboardBalanceMovementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kpi-performance': {
      id: '/dashboard/kpi-performance'
      path: '/kpi-performance'
      fullPath: '/dashboard/kpi-performance'
      preLoaderRoute: typeof DashboardKpiPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAllDsasRoute: typeof DashboardAllDsasRoute
  DashboardBalanceMovementsRoute: typeof DashboardBalanceMovementsRoute
  DashboardKpiPerformanceRoute: typeof DashboardKpiPerformanceRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAllDsasRoute: DashboardAllDsasRoute,
  DashboardBalanceMovementsRoute: DashboardBalanceMovementsRoute,
  DashboardKpiPerformanceRoute: DashboardKpiPerformanceRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CreatePasswordRoute: CreatePasswordRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  PasswordResetSuccessRoute: PasswordResetSuccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
